theme = "gruvbox"

[editor]
cursorline = true
color-modes = true
scrolloff = 5
true-color = true
clipboard-provider = "wayland"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
character = ":"

[keys.normal]
"y" = ["yank", "yank_main_selection_to_clipboard"]
"p" = ["paste_clipboard_after"]
